# Dockerfile.bun
FROM oven/bun:latest

WORKDIR /home/app

COPY package.json .
COPY bun.lock .


# Only install prod dependencies if you're building a production image
# For development, 'bun install' handles dev dependencies too
RUN bun install

COPY . .

EXPOSE 4006

CMD [ "bun", "run", "dev" ]
