apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app: {{ include "gateway.name" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gateway.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "gateway.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3001
              protocol: TCP
          env:
            - name: AUTH_GRPC_URL
              value: {{ .Values.env.AUTH_GRPC_URL | quote }}
            - name: USER_GRPC_URL
              value: {{ .Values.env.USER_GRPC_URL | quote }}
            - name: GIG_GRPC_URL
              value: {{ .Values.env.GIG_GRPC_URL | quote }}
            - name: CHAT_GRPC_URL
              value: {{ .Values.env.CHAT_GRPC_URL | quote }}
            - name: CLIENT_URL
              value: {{ .Values.env.CLIENT_URL | quote }}
          envFrom:
            - secretRef:
                name: {{ include "gateway.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
