replicaCount: 1

image:
  repository: asiful087/kaj-bazar-auth
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 50051

secrets:
  DATABASE_URL: ""
  ACCESS_TOKEN_SECRET: ""
  ACCESS_TOKEN_EXPIRATION: "5m"
  REFRESH_TOKEN_SECRET: ""
  REFRESH_TOKEN_EXPIRATION: "7d"
  GATEWAY_SECRET: ""
  RABBITMQ_URL: ""
  CLIENT_URL: ""

env:
  GRPC_PORT: "50051"
