name: kaj-bazar-dev

services:
  # ==================================== Infrastructure ==============================
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    # No user mapping needed for standard infra services

  auth-db:
    container_name: auth_postgres_container
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PWD}
      - POSTGRES_DB=${PG_DB_NAME}

  user-postgres:
    container_name: user_postgres_container
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PWD}
      - POSTGRES_DB=${PG_DB_NAME}

  gig-postgres:
    container_name: gig_postgres_container
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PWD}
      - POSTGRES_DB=${PG_DB_NAME}

  chat-postgres:
    container_name: chat_postgres_container
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PWD}
      - POSTGRES_DB=${PG_DB_NAME}

  order-db:
    container_name: order_postgres_container
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PWD}
      - POSTGRES_DB=${PG_DB_NAME}

  review-db:
    container_name: review_postgres_container
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PWD}
      - POSTGRES_DB=${PG_DB_NAME}

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=kaj_bazar
      - RABBITMQ_DEFAULT_PASS=kaj_bazarpass
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    # No user mapping needed for standard infra services

  # ==================================== Application Services ==============================

  client:
    container_name: client_container
    build:
      context: client
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_BASE_ENDPOINT=${BASE_ENDPOINT}
      - NEXT_PUBLIC_SOCKET_ENDPOINT=${SOCKET_ENDPOINT}
    volumes:
      - ./client:/home/app
      - /home/app/node_modules
    depends_on:
      - gateway
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  gateway:
    container_name: gateway_container
    build:
      context: gateway-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:4000
    environment:
      - GATEWAY_JWT_TOKEN=${GATEWAY_JWT_TOKEN}
      - JWT_TOKEN=${JWT_TOKEN}
      - NODE_ENV=${NODE_ENV}
      - SECRET_KEY_ONE=${SECRET_KEY_ONE}
      - SECRET_KEY_TWO=${SECRET_KEY_TWO}
      - CLIENT_URL=${CLIENT_URL}
      - AUTH_BASE_URL=${AUTH_BASE_URL}
      - USER_BASE_URL=${USER_BASE_URL}
      - GIG_BASE_URL=${GIG_BASE_URL}
      - CHAT_BASE_URL=${CHAT_BASE_URL}
      - ORDER_BASE_URL=${ORDER_BASE_URL}
      - REVIEW_BASE_URL=${REVIEW_BASE_URL}
      - REDIS_HOST=${REDIS_HOST}
    volumes:
      - ./gateway-service:/home/app
      - /home/app/node_modules
    depends_on:
      - redis
      - chat
      - order
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  email:
    container_name: email_container
    build:
      context: email-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4001:4001
    environment:
      - ENABLE_APM=${ENABLE_APM}
      - NODE_ENV=${NODE_ENV}
      - CLIENT_URL=${CLIENT_URL}
      - RABBITMQ_ENDPOINT=${RABBITMQ_ENDPOINT}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_EMAIL_PASSWORD=${SENDER_EMAIL_PASSWORD}
    volumes:
      - ./email-service:/home/app
      - /home/app/node_modules
    depends_on:
      rabbitmq:
        condition: service_healthy
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  auth:
    container_name: auth_container
    build:
      context: auth-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4002:4002
    environment:
      - ENABLE_APM=${ENABLE_APM}
      - GATEWAY_JWT_TOKEN=${GATEWAY_JWT_TOKEN}
      - JWT_TOKEN=${JWT_TOKEN}
      - NODE_ENV=${NODE_ENV}
      - CLIENT_URL=${CLIENT_URL}
      - API_GATEWAY_URL=${API_GATEWAY_URL}
      - RABBITMQ_ENDPOINT=${RABBITMQ_ENDPOINT}
      - DATABASE_URL=${AUTH_DB_URL}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
    volumes:
      - ./auth-service:/home/app
      - /home/app/node_modules
    depends_on:
      auth-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  user:
    container_name: user_container
    build:
      context: user-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4003:4003
    environment:
      - ENABLE_APM=${ENABLE_APM}
      - GATEWAY_JWT_TOKEN=${GATEWAY_JWT_TOKEN}
      - JWT_TOKEN=${JWT_TOKEN}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${USER_DB_URL}
      - API_GATEWAY_URL=${API_GATEWAY_URL}
      - RABBITMQ_ENDPOINT=${RABBITMQ_ENDPOINT}
      - REDIS_HOST=${REDIS_HOST}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
    volumes:
      - ./user-service:/home/app
      - /home/app/node_modules
    depends_on:
      user-postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  gig:
    container_name: gig_container
    build:
      context: gig-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4004:4004
    environment:
      - ENABLE_APM=${ENABLE_APM}
      - GATEWAY_JWT_TOKEN=${GATEWAY_JWT_TOKEN}
      - JWT_TOKEN=${JWT_TOKEN}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${GIG_DB_URL}
      - API_GATEWAY_URL=${API_GATEWAY_URL}
      - RABBITMQ_ENDPOINT=${RABBITMQ_ENDPOINT}
      - REDIS_HOST=${REDIS_HOST}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
    volumes:
      - ./gig-service:/home/app
      - /home/app/node_modules
    depends_on:
      gig-postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  chat:
    container_name: chat_container
    build:
      context: chat-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4005:4005
    environment:
      - ENABLE_APM=${ENABLE_APM}
      - GATEWAY_JWT_TOKEN=${GATEWAY_JWT_TOKEN}
      - JWT_TOKEN=${JWT_TOKEN}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${CHAT_DB_URL}
      - API_GATEWAY_URL=${API_GATEWAY_URL}
      - RABBITMQ_ENDPOINT=${RABBITMQ_ENDPOINT}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
      - REDIS_HOST=${REDIS_HOST}
    volumes:
      - ./chat-service:/home/app
      - /home/app/node_modules
    depends_on:
      chat-postgres:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  order:
    container_name: order_container
    build:
      context: order-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4006:4006
    environment:
      - ENABLE_APM=${ENABLE_APM}
      - GATEWAY_JWT_TOKEN=${GATEWAY_JWT_TOKEN}
      - JWT_TOKEN=${JWT_TOKEN}
      - NODE_ENV=${NODE_ENV}
      - CLIENT_URL=${CLIENT_URL}
      - DATABASE_URL=${ORDER_DB_URL}
      - API_GATEWAY_URL=${API_GATEWAY_URL}
      - RABBITMQ_ENDPOINT=${RABBITMQ_ENDPOINT}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
    volumes:
      - ./order-service:/home/app
      - /home/app/node_modules
    depends_on:
      order-db:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  review:
    container_name: review_container
    build:
      context: review-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4007:4007
    environment:
      - ENABLE_APM=${ENABLE_APM}
      - DATABASE_URL=${REVIEW_DB_URL}
      - GATEWAY_JWT_TOKEN=${GATEWAY_JWT_TOKEN}
      - JWT_TOKEN=${JWT_TOKEN}
      - NODE_ENV=${NODE_ENV}
      - API_GATEWAY_URL=${API_GATEWAY_URL}
      - RABBITMQ_ENDPOINT=${RABBITMQ_ENDPOINT}
    volumes:
      - ./review-service:/home/app
      - /home/app/node_modules
    depends_on:
      review-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  # ==================================== Studio Services ==============================

  auth-studio:
    container_name: auth_studio_container
    build:
      context: auth-service
      dockerfile: Dockerfile.studio
    restart: always
    ports:
      - 4983:4983
    environment:
      - DATABASE_URL=${AUTH_DB_URL}
    profiles: ["exclude"]
    volumes:
      - ./auth-service:/home/app
    depends_on:
      - auth-db
      - auth
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  user-studio:
    container_name: user_studio_container
    build:
      context: user-service
      dockerfile: Dockerfile.studio
    restart: always
    ports:
      - 4984:4984
    environment:
      - DATABASE_URL=${USER_DB_URL}
    profiles: ["exclude"]
    volumes:
      - ./user-service:/home/app
    depends_on:
      - user-postgres
      - user
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  gig-studio:
    container_name: gig_studio_container
    build:
      context: gig-service
      dockerfile: Dockerfile.studio
    restart: always
    ports:
      - 4985:4985
    environment:
      - DATABASE_URL=${GIG_DB_URL}
    profiles: ["exclude"]
    volumes:
      - ./gig-service:/home/app
    depends_on:
      - gig-postgres
      - gig
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  chat-studio:
    container_name: chat_studio_container
    build:
      context: chat-service
      dockerfile: Dockerfile.studio
    restart: always
    ports:
      - 4986:4986
    environment:
      - DATABASE_URL=${CHAT_DB_URL}
    profiles: ["exclude"]
    volumes:
      - ./chat-service:/home/app
    depends_on:
      - chat-postgres
      - chat
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  order-studio:
    container_name: order_studio_container
    build:
      context: order-service
      dockerfile: Dockerfile.studio
    restart: always
    ports:
      - 4987:4987
    environment:
      - DATABASE_URL=${ORDER_DB_URL}
    profiles: ["exclude"]
    volumes:
      - ./order-service:/home/app
    depends_on:
      - order-db
      - order
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"

  review-studio:
    container_name: review_studio_container
    build:
      context: review-service
      dockerfile: Dockerfile.studio
    restart: always
    ports:
      - 4988:4988
    environment:
      - DATABASE_URL=${REVIEW_DB_URL}
    profiles: ["exclude"]
    volumes:
      - ./review-service:/home/app
    depends_on:
      - review-db
      - review
    # 🌟 ADDED UID/GID MAPPING 🌟
    user: "${UID}:${GID}"
