apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    app: {{ include "auth.name" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  ACCESS_TOKEN_SECRET: {{ .Values.secrets.ACCESS_TOKEN_SECRET | quote }}
  ACCESS_TOKEN_EXPIRATION: {{ .Values.secrets.ACCESS_TOKEN_EXPIRATION | quote }}
  REFRESH_TOKEN_SECRET: {{ .Values.secrets.REFRESH_TOKEN_SECRET | quote }}
  REFRESH_TOKEN_EXPIRATION: {{ .Values.secrets.REFRESH_TOKEN_EXPIRATION | quote }}
  GATEWAY_SECRET: {{ .Values.secrets.GATEWAY_SECRET | quote }}
  RABBITMQ_URL: {{ .Values.secrets.RABBITMQ_URL | quote }}
  CLIENT_URL: {{ .Values.secrets.CLIENT_URL | quote }}
