apiVersion: v1
kind: Service
metadata:
  name: {{ include "gig.fullname" . }}
  labels:
    app: {{ include "gig.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.env.GRPC_PORT }}
      protocol: TCP
      name: grpc
  selector:
    app: {{ include "gig.name" . }}
    release: {{ .Release.Name }}
