replicaCount: 1

image:
  repository: asiful087/kaj-bazar-chat
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 50054

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

secrets:
  DATABASE_URL: "postgresql://billu:password@chat-db:5432/chat"
  ACCESS_TOKEN_SECRET: ""
  ACCESS_TOKEN_EXPIRATION: "5m"
  GATEWAY_SECRET: ""
  REDIS_HOST: "redis"

env:
  GRPC_PORT: "50054"
