CREATE TABLE "gigs_table" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"seller_id" uuid NOT NULL,
	"username" text NOT NULL,
	"email" text NOT NULL,
	"profile_picture" text,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"basic_title" text NOT NULL,
	"basic_description" text NOT NULL,
	"category" text NOT NULL,
	"sub_categories" text[] NOT NULL,
	"tags" text[],
	"active" boolean DEFAULT true NOT NULL,
	"expected_delivery" text NOT NULL,
	"ratings_count" integer DEFAULT 0 NOT NULL,
	"rating_sum" integer DEFAULT 0 NOT NULL,
	"rating_categories" jsonb DEFAULT '{"five":{"star":0,"count":0},"four":{"star":0,"count":0},"three":{"star":0,"count":0},"two":{"star":0,"count":0},"one":{"star":0,"count":0}}'::jsonb NOT NULL,
	"price" integer DEFAULT 0 NOT NULL,
	"sort_id" integer,
	"cover_image" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
