replicaCount: 1

image:
  repository: asiful087/kaj-bazar-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

secrets:
  ACCESS_TOKEN_SECRET: ""
  ACCESS_TOKEN_EXPIRATION: "5m"
  REFRESH_TOKEN_SECRET: ""
  REFRESH_TOKEN_EXPIRATION: "7d"
  AUTH_GATEWAY_SECRET: ""
  USER_GATEWAY_SECRET: ""
  GIG_GATEWAY_SECRET: ""
  CHAT_GATEWAY_SECRET: ""
  ORDER_GATEWAY_SECRET: ""
  REVIEW_GATEWAY_SECRET: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""

env:
  AUTH_GRPC_URL: "auth:50051"
  USER_GRPC_URL: "user:50052"
  GIG_GRPC_URL: "gig:50053"
  CHAT_GRPC_URL: "chat:50054"
  CLIENT_URL: "http://localhost:3000"
