import type { Metadata } from "next";
import { Roboto, Rhodium_Libre } from "next/font/google";
import "./globals.css";
import Footer from "@/components/widgets/footer";
import Container from "@/components/container";
import Header from "@/components/widgets/header";
import Providers from "@/providers";

// const inter = Inter({
//   variable: "--font-inter",
//   weight: ["400", "700"],
// });

// const poppings = Poppins({
//   variable: "--font-poppins",
//   weight: ["400", "500", "700"],
// });

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-robot",
  weight: ["300", "400", "500", "700"],
});

const rodium_libre = Rhodium_Libre({
  subsets: ["latin"],
  variable: "--font-rodium-libre",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${rodium_libre.variable} font-roboto bg-[#F4F3F2] antialiased`}
      >
        <Providers>
          <Header />

          {children}

          <Container className="bg-white">
            <Footer />
          </Container>
        </Providers>
      </body>
    </html>
  );
}
