import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ReactQueryProvider from "@/providers/react-query-provider";
import AuthProvider from "@/providers/auth.provider";
import Footer from "@/components/footer";
import Container from "@/components/container";

// const inter = Inter({
//   variable: "--font-inter",
//   weight: ["400", "700"],
// });

// const poppings = Poppins({
//   variable: "--font-poppins",
//   weight: ["400", "500", "700"],
// });

const roboto = Roboto({
  variable: "--font-robot",
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}  bg-[#F4F3F2] antialiased`}>
        <Toaster />
        <ReactQueryProvider>
          <AuthProvider>
            <Container>{children}</Container>
          </AuthProvider>
        </ReactQueryProvider>

        {/* <Footer /> */}
      </body>
    </html>
  );
}
