import type { Metadata } from "next";
import { Roboto, Rhodium_Libre } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ReactQueryProvider from "@/providers/react-query-provider";
import AuthProvider from "@/providers/auth.provider";
import Footer from "@/components/widgets/footer";
import Container from "@/components/container";
import Navigation from "@/components/Navigation";
import Header from "@/components/widgets/header";
import { config } from "@/config";

// const inter = Inter({
//   variable: "--font-inter",
//   weight: ["400", "700"],
// });

// const poppings = Poppins({
//   variable: "--font-poppins",
//   weight: ["400", "500", "700"],
// });

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-robot",
  weight: ["300", "400", "500", "700"],
});

const rodium_libre = Rhodium_Libre({
  subsets: ["latin"],
  variable: "--font-rodium-libre",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("the base url is layout - ", config.API_GATEWAY_URL);
  // console.log("hello", config.API_GATEWAY_URL);

  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${rodium_libre.variable} font-roboto bg-[#F4F3F2] antialiased`}
      >
        <Toaster />
        <ReactQueryProvider>
          <AuthProvider>
            {/* <Container>{children}</Container> */}

            {/* <Container className="mt-[24px]"> */}
            {/* <Navigation /> */}
            <Header />

            {/* </Container> */}
            {children}
            <Container className="mt-[100px] bg-white">
              <Footer />
            </Container>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
