FROM node:21-alpine3.18

WORKDIR /home/app

COPY package*.json .

# RUN npm install
# RUN npm install drizzle-kit@0.31.4 drizzle-orm@0.44.2 mysql2@3.14.1


COPY . . 

EXPOSE 4983

CMD ["npx", "drizzle-kit", "studio", "--host", "0.0.0.0", "--port", "4983" ]
