apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "email.fullname" . }}
  labels:
    app: {{ include "email.name" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "email.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "email.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: email
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "email.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
