apiVersion: v1
kind: Secret
metadata:
  name: {{ include "email.fullname" . }}
  labels:
    app: {{ include "email.name" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  SENDER_EMAIL: {{ .Values.secrets.SENDER_EMAIL | quote }}
  SENDER_EMAIL_PASSWORD: {{ .Values.secrets.SENDER_EMAIL_PASSWORD | quote }}
  RABBITMQ_URL: {{ .Values.secrets.RABBITMQ_URL | quote }}
  CLIENT_URL: {{ .Values.secrets.CLIENT_URL | quote }}
