apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chat.fullname" . }}
  labels:
    app: {{ include "chat.name" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  ACCESS_TOKEN_SECRET: {{ .Values.secrets.ACCESS_TOKEN_SECRET | quote }}
  ACCESS_TOKEN_EXPIRATION: {{ .Values.secrets.ACCESS_TOKEN_EXPIRATION | quote }}
  GATEWAY_SECRET: {{ .Values.secrets.GATEWAY_SECRET | quote }}
  REDIS_HOST: {{ .Values.secrets.REDIS_HOST | quote }}
