# {{$guid}} for a random ID 
# {{$timestamp}} for the current time.

@baseUrl = http://localhost:3001/auth
@authToken = your_token_here

### Register

POST {{baseUrl}}/register
Content-Type: application/json

{
  "username": "mridul_dev",
  "email": "mridul@example.com",
  "password": "SecurePassword123!",
  "country": "Bangladesh",
  "profilePicture": "https://example.com/profiles/mridul_dev.jpg"
}


### Resend Verification Link

POST {{baseUrl}}/resend-verification-link
Content-Type: application/json

{
  "email": "mridul@example.com"
}


### Verify Email

PUT {{baseUrl}}/verify-email
Content-Type: application/json

{
  "token": "e922dfa39dcbaf507ec1660419e6e11d877d0445"
}

### Login

POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "mridul@example.com",
  "password": "SecurePassword123!"
  # "password": "SecurePassword123!!"
}

### Forgot Password

PUT {{baseUrl}}/forgot-password
Content-Type: application/json

{
  "email": "mridul@example.com"
}


### Reset Password

PUT {{baseUrl}}/reset-password
Content-Type: application/json

{
  "token": "bcf7abd7d38557496af0f0840b717123b61fad10",
  "password": "SecurePassword123!!"
}


### Change Password

PUT {{baseUrl}}/change-password
Content-Type: application/json

{
  "email": "mridul@example.com",
  "password": "SecurePassword123!"
}


### Current User
GET {{baseUrl}}/who-am-i
Content-Type: application/json
