# {{$guid}} for a random ID 
# {{$timestamp}} for the current time.

@baseUrl = http://localhost:3001/buyer


### Current Buyer
GET {{baseUrl}}/current-buyer
Content-Type: application/json


### Buyer by id
GET {{baseUrl}}/id/81b98a70-fb9e-488e-9b90-222dfa0ec5c3
Content-Type: application/json



### Buyer by name
GET {{baseUrl}}/username/mridul_dev
Content-Type: application/json
