export const config = {
  JWT_TOKEN: process.env.JWT_TOKEN || "1234",
  GATEWAY_JWT_TOKEN: process.env.GATEWAY_JWT_TOKEN || "1234",
  NODE_ENV: process.env.NODE_ENV || "",
  SECRET_KEY_ONE: process.env.SECRET_KEY_ONE || "",
  SECRET_KEY_TWO: process.env.SECRET_KEY_TWO || "",
  CLIENT_URL: process.env.CLIENT_URL || "",
  AUTH_BASE_URL: process.env.AUTH_BASE_URL || "",
  USER_BASE_URL: process.env.USER_BASE_URL || "",
  GIG_BASE_URL: process.env.GIG_BASE_URL || "",
  CHAT_BASE_URL: process.env.CHAT_BASE_URL || "",
  ORDER_BASE_URL: process.env.ORDER_BASE_URL || "",
  REVIEW_BASE_URL: process.env.REVIEW_BASE_URL || "",
  REDIS_HOST: process.env.REDIS_HOST || "",
};
