# FROM oven/bun:1.2.14-alpine3.18
# FROM oven/bun:1.0-alpine

FROM node:21-alpine3.18

WORKDIR /app

COPY package.json .
# RUN bun install
RUN npm install

COPY . .


EXPOSE 4002

# CMD [ "bun", "run", "dev" ]
CMD [ "npm", "run", "dev" ]
