name: Deploy Gateway

on:
  push:
    branches: [nest-microservice]
    paths:
      - 'apps/gateway/**'
      - 'charts/gateway/**'
      - 'packages/common/**'
      - '.github/workflows/deploy-gateway.yml'
  pull_request:
    branches: [nest-microservice]
    paths:
      - 'apps/gateway/**'
      - 'charts/gateway/**'
      - 'packages/common/**'
      - '.github/workflows/deploy-gateway.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Short Git SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/gateway/Dockerfile
          target: production
          push: true
          tags: |
            asiful087/kaj-bazar-gateway:${{ steps.vars.outputs.sha_short }}
            asiful087/kaj-bazar-gateway:latest

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        env:
          ACCESS_TOKEN_SECRET: ${{ secrets.GATEWAY_ACCESS_TOKEN_SECRET }}
          ACCESS_TOKEN_EXPIRATION: ${{ secrets.GATEWAY_ACCESS_TOKEN_EXPIRATION }}
          REFRESH_TOKEN_SECRET: ${{ secrets.GATEWAY_REFRESH_TOKEN_SECRET }}
          REFRESH_TOKEN_EXPIRATION: ${{ secrets.GATEWAY_REFRESH_TOKEN_EXPIRATION }}
          AUTH_GATEWAY_SECRET: ${{ secrets.GATEWAY_AUTH_GATEWAY_SECRET }}
          USER_GATEWAY_SECRET: ${{ secrets.GATEWAY_USER_GATEWAY_SECRET }}
          GIG_GATEWAY_SECRET: ${{ secrets.GATEWAY_GIG_GATEWAY_SECRET }}
          CHAT_GATEWAY_SECRET: ${{ secrets.GATEWAY_CHAT_GATEWAY_SECRET }}
          ORDER_GATEWAY_SECRET: ${{ secrets.GATEWAY_ORDER_GATEWAY_SECRET }}
          REVIEW_GATEWAY_SECRET: ${{ secrets.GATEWAY_REVIEW_GATEWAY_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GATEWAY_GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GATEWAY_GOOGLE_CLIENT_SECRET }}
          AUTH_GRPC_URL: ${{ secrets.GATEWAY_AUTH_GRPC_URL }}
          USER_GRPC_URL: ${{ secrets.GATEWAY_USER_GRPC_URL }}
          GIG_GRPC_URL: ${{ secrets.GATEWAY_GIG_GRPC_URL }}
          CHAT_GRPC_URL: ${{ secrets.GATEWAY_CHAT_GRPC_URL }}
          CLIENT_URL: ${{ secrets.GATEWAY_CLIENT_URL }}
          GATEWAY_URL: ${{ secrets.GATEWAY_GATEWAY_URL }}
        run: |
          cat <<EOF > secrets.tmp.yaml
          secrets:
            ACCESS_TOKEN_SECRET: "$ACCESS_TOKEN_SECRET"
            ACCESS_TOKEN_EXPIRATION: "$ACCESS_TOKEN_EXPIRATION"
            REFRESH_TOKEN_SECRET: "$REFRESH_TOKEN_SECRET"
            REFRESH_TOKEN_EXPIRATION: "$REFRESH_TOKEN_EXPIRATION"
            AUTH_GATEWAY_SECRET: "$AUTH_GATEWAY_SECRET"
            USER_GATEWAY_SECRET: "$USER_GATEWAY_SECRET"
            GIG_GATEWAY_SECRET: "$GIG_GATEWAY_SECRET"
            CHAT_GATEWAY_SECRET: "$CHAT_GATEWAY_SECRET"
            ORDER_GATEWAY_SECRET: "$ORDER_GATEWAY_SECRET"
            REVIEW_GATEWAY_SECRET: "$REVIEW_GATEWAY_SECRET"
            GOOGLE_CLIENT_ID: "$GOOGLE_CLIENT_ID"
            GOOGLE_CLIENT_SECRET: "$GOOGLE_CLIENT_SECRET"
            AUTH_GRPC_URL: "$AUTH_GRPC_URL"
            USER_GRPC_URL: "$USER_GRPC_URL"
            GIG_GRPC_URL: "$GIG_GRPC_URL"
            CHAT_GRPC_URL: "$CHAT_GRPC_URL"
            CLIENT_URL: "$CLIENT_URL"
            GATEWAY_URL: "$GATEWAY_URL"
          EOF

          helm upgrade --install kajbazar-gateway ./charts/gateway \
            --namespace kaj-bazar --create-namespace \
            --set image.tag=${{ steps.vars.outputs.sha_short }} \
            --values secrets.tmp.yaml \
            --wait

          rm -f secrets.tmp.yaml
