name: deploy-gig-service

on:
  push:
    branches:
      - main
    paths:
      - "5-gig-service/**"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Transfer code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./5-gig-service
          file: ./5-gig-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kaj-bazar-gig:latest
